# Generated by Django 2.2.3 on 2020-04-13 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0010_auto_20200413_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='unsuccessful_attempts',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
